openapi: 3.0.0
info:
  title: Standar User Management
  version: 1.0.0
servers:
  - url: http://{{baseurl}}
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
    noauthAuth:
      type: http
      scheme: noauth
tags:
  - name: Auth
  - name: Auth > Profile
  - name: User Management
  - name: User Management > Master User
  - name: User Management > Master Role
paths:
  /api/user/profile:
    get:
      tags:
        - Auth > Profile
      summary: Get User Profile
      security:
        - bearerAuth: []
      responses:
        '200':
          description: OK
          headers:
            Vary:
              schema:
                type: string
                example: Access-Control-Request-Headers
            X-Content-Type-Options:
              schema:
                type: string
                example: nosniff
            X-XSS-Protection:
              schema:
                type: integer
                example: '0'
            Cache-Control:
              schema:
                type: string
                example: no-cache, no-store, max-age=0, must-revalidate
            Pragma:
              schema:
                type: string
                example: no-cache
            Expires:
              schema:
                type: integer
                example: '0'
            X-Frame-Options:
              schema:
                type: string
                example: DENY
            Content-Type:
              schema:
                type: string
                example: application/json
            Transfer-Encoding:
              schema:
                type: string
                example: chunked
            Date:
              schema:
                type: string
                example: Fri, 06 Dec 2024 06:58:41 GMT
            Keep-Alive:
              schema:
                type: string
                example: timeout=60
            Connection:
              schema:
                type: string
                example: keep-alive
          content:
            application/json:
              schema:
                type: object
              example:
                response_schema:
                  response_code: PLUGINUSERMANAGEMENT-0000
                  response_message: Success
                response_output:
                  detail:
                    name: Super Admin
                    permissions:
                      - MASTER_USER.DELETE
                      - MASTER_USER.READ_LIST
                      - MASTER_ROLE.READ_DETAIL
                      - MASTER_USER.CREATE
                      - MASTER_ROLE.UPDATE
                      - MASTER_USER.UPDATE
                      - MASTER_ROLE.READ_LIST
                      - MENU_X.ACTION_A
                      - MENU_X.ACTION_B
                      - MASTER_ROLE.CREATE
                      - MASTER_ROLE.DELETE
                      - MASTER_USER.READ_DETAIL
  /api/user/profile/create-password:
    post:
      tags:
        - Auth > Profile
      summary: Create New Password
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                new_password: P@ssword!12
      security:
        - bearerAuth: []
      responses:
        '200':
          description: OK
          headers:
            Vary:
              schema:
                type: string
                example: Access-Control-Request-Headers
            X-Content-Type-Options:
              schema:
                type: string
                example: nosniff
            X-XSS-Protection:
              schema:
                type: integer
                example: '0'
            Cache-Control:
              schema:
                type: string
                example: no-cache, no-store, max-age=0, must-revalidate
            Pragma:
              schema:
                type: string
                example: no-cache
            Expires:
              schema:
                type: integer
                example: '0'
            X-Frame-Options:
              schema:
                type: string
                example: DENY
            Content-Type:
              schema:
                type: string
                example: application/json
            Transfer-Encoding:
              schema:
                type: string
                example: chunked
            Date:
              schema:
                type: string
                example: Fri, 06 Dec 2024 16:08:39 GMT
            Keep-Alive:
              schema:
                type: string
                example: timeout=60
            Connection:
              schema:
                type: string
                example: keep-alive
          content:
            application/json:
              schema:
                type: object
              example:
                response_schema:
                  response_code: PLUGINUSERMANAGEMENT-0000
                  response_message: Success
                response_output:
                  detail: null
  /api/user/profile/change-password:
    put:
      tags:
        - Auth > Profile
      summary: Change Password
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                old_password: P@ssword12!!
                new_password: P@ssword33!!
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /api/auth/login:
    post:
      tags:
        - Auth
      summary: Login
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                username: super_admin
                password: P@ssword33!!
      responses:
        '200':
          description: OK
          headers:
            Vary:
              schema:
                type: string
                example: Access-Control-Request-Headers
            X-Content-Type-Options:
              schema:
                type: string
                example: nosniff
            X-XSS-Protection:
              schema:
                type: integer
                example: '0'
            Cache-Control:
              schema:
                type: string
                example: no-cache, no-store, max-age=0, must-revalidate
            Pragma:
              schema:
                type: string
                example: no-cache
            Expires:
              schema:
                type: integer
                example: '0'
            X-Frame-Options:
              schema:
                type: string
                example: DENY
            Content-Type:
              schema:
                type: string
                example: application/json
            Transfer-Encoding:
              schema:
                type: string
                example: chunked
            Date:
              schema:
                type: string
                example: Fri, 06 Dec 2024 06:26:32 GMT
            Keep-Alive:
              schema:
                type: string
                example: timeout=60
            Connection:
              schema:
                type: string
                example: keep-alive
          content:
            application/json:
              schema:
                type: object
              example:
                response_schema:
                  response_code: PLUGINUSERMANAGEMENT-0000
                  response_message: Success
                response_output:
                  detail:
                    access_token: >-
                      eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJNUT09IiwidHlwZSI6IkFDQ0VTU19UT0tFTiIsInNlc3Npb25JZCI6ImYyNmQ5YzZjLTc4MDMtNGZlMC04ZWNmLWY2MGU1NzU4MDUzMSIsImF1dGhvcml0aWVzIjpbIk1BU1RFUl9VU0VSLkRFTEVURSIsIk1BU1RFUl9VU0VSLlJFQURfTElTVCIsIk1BU1RFUl9ST0xFLlJFQURfREVUQUlMIiwiTUFTVEVSX1VTRVIuQ1JFQVRFIiwiTUFTVEVSX1JPTEUuVVBEQVRFIiwiTUFTVEVSX1VTRVIuVVBEQVRFIiwiTUFTVEVSX1JPTEUuUkVBRF9MSVNUIiwiTUVOVV9YLkFDVElPTl9BIiwiTUVOVV9YLkFDVElPTl9CIiwiTUFTVEVSX1JPTEUuQ1JFQVRFIiwiTUFTVEVSX1JPTEUuREVMRVRFIiwiTUFTVEVSX1VTRVIuUkVBRF9ERVRBSUwiXSwiZXhwIjoxNzMzNDY5MzkyfQ.XZoGrgKbDJ1dgwOqZSZnCo8Sz9DWhrLNz_PE25RNBDVq2YI8BU5OEqshHG-5lWj1SMmyNTYj-c1XmD5JLi22zw
                    refresh_token: >-
                      eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJNUT09IiwidHlwZSI6IlJFRlJFU0hfVE9LRU4iLCJzZXNzaW9uSWQiOiJmMjZkOWM2Yy03ODAzLTRmZTAtOGVjZi1mNjBlNTc1ODA1MzEiLCJleHAiOjE3MzM0NzM1OTJ9.ahrDEYtFs0u2uubWkylLvdudDvAy-XRLLtzwgBP16OMUiXVaBb6aVceJrH-WnDp2gh2rnf4V5aMi5q8SAa2tyg
                    token_type: Bearer
                    need_change_password: false
                    expires_in: 3000000
  /api/auth/refresh-token:
    post:
      tags:
        - Auth
      summary: Refresh Token
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                refresh_token: '{{refresh_token}}'
      security:
        - noauthAuth: []
      parameters:
        - name: ''
          in: header
          schema:
            type: string
      responses:
        '200':
          description: OK
          headers:
            Vary:
              schema:
                type: string
                example: Access-Control-Request-Headers
            X-Content-Type-Options:
              schema:
                type: string
                example: nosniff
            X-XSS-Protection:
              schema:
                type: integer
                example: '0'
            Cache-Control:
              schema:
                type: string
                example: no-cache, no-store, max-age=0, must-revalidate
            Pragma:
              schema:
                type: string
                example: no-cache
            Expires:
              schema:
                type: integer
                example: '0'
            X-Frame-Options:
              schema:
                type: string
                example: DENY
            Content-Type:
              schema:
                type: string
                example: application/json
            Transfer-Encoding:
              schema:
                type: string
                example: chunked
            Date:
              schema:
                type: string
                example: Fri, 06 Dec 2024 06:56:53 GMT
            Keep-Alive:
              schema:
                type: string
                example: timeout=60
            Connection:
              schema:
                type: string
                example: keep-alive
          content:
            application/json:
              schema:
                type: object
              example:
                response_schema:
                  response_code: PLUGINUSERMANAGEMENT-0000
                  response_message: Success
                response_output:
                  detail:
                    access_token: >-
                      eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJNUT09IiwidHlwZSI6IkFDQ0VTU19UT0tFTiIsInNlc3Npb25JZCI6ImYyNmQ5YzZjLTc4MDMtNGZlMC04ZWNmLWY2MGU1NzU4MDUzMSIsImF1dGhvcml0aWVzIjpbIk1BU1RFUl9VU0VSLkRFTEVURSIsIk1BU1RFUl9VU0VSLlJFQURfTElTVCIsIk1BU1RFUl9ST0xFLlJFQURfREVUQUlMIiwiTUFTVEVSX1VTRVIuQ1JFQVRFIiwiTUFTVEVSX1JPTEUuVVBEQVRFIiwiTUFTVEVSX1VTRVIuVVBEQVRFIiwiTUFTVEVSX1JPTEUuUkVBRF9MSVNUIiwiTUVOVV9YLkFDVElPTl9BIiwiTUVOVV9YLkFDVElPTl9CIiwiTUFTVEVSX1JPTEUuQ1JFQVRFIiwiTUFTVEVSX1JPTEUuREVMRVRFIiwiTUFTVEVSX1VTRVIuUkVBRF9ERVRBSUwiXSwiZXhwIjoxNzMzNDcxMjEzfQ.80ITrDqgEfALj6zBYIynsYv8a0kvzW3KFDgB7Ta4jHyAkfmrTBI-BNiZmdgJRw11f-ue5oIhB1x8MrGGmblneg
                    token_type: Bearer
  /api/user/all:
    get:
      tags:
        - User Management > Master User
      summary: Get All User
      security:
        - bearerAuth: []
      parameters:
        - name: search
          in: query
          schema:
            type: string
        - name: is-active
          in: query
          schema:
            type: boolean
          example: 'true'
      responses:
        '200':
          description: OK
          headers:
            Vary:
              schema:
                type: string
                example: Access-Control-Request-Headers
            X-Content-Type-Options:
              schema:
                type: string
                example: nosniff
            X-XSS-Protection:
              schema:
                type: integer
                example: '0'
            Cache-Control:
              schema:
                type: string
                example: no-cache, no-store, max-age=0, must-revalidate
            Pragma:
              schema:
                type: string
                example: no-cache
            Expires:
              schema:
                type: integer
                example: '0'
            X-Frame-Options:
              schema:
                type: string
                example: DENY
            Content-Type:
              schema:
                type: string
                example: application/json
            Transfer-Encoding:
              schema:
                type: string
                example: chunked
            Date:
              schema:
                type: string
                example: Fri, 06 Dec 2024 16:10:48 GMT
            Keep-Alive:
              schema:
                type: string
                example: timeout=60
            Connection:
              schema:
                type: string
                example: keep-alive
          content:
            application/json:
              schema:
                type: object
              example:
                response_schema:
                  response_code: PLUGINUSERMANAGEMENT-0000
                  response_message: Success
                response_output:
                  list:
                    pagination: null
                    content:
                      - id: 1
                        username: super_admin
                        name: Super Admin
                        is_active: true
                        created_at: '2024-11-25T07:28:33.959202Z'
                        created_by: null
                        last_modified_at: '2024-12-06T16:08:39.55261Z'
                        last_modified_by: null
  /api/user:
    get:
      tags:
        - User Management > Master User
      summary: Get User Pagination
      security:
        - bearerAuth: []
      parameters:
        - name: search
          in: query
          schema:
            type: string
        - name: is-active
          in: query
          schema:
            type: boolean
          example: 'true'
        - name: page
          in: query
          schema:
            type: integer
          example: '0'
        - name: size
          in: query
          schema:
            type: integer
          example: '10'
        - name: sort
          in: query
          schema:
            type: string
          example: name,asc
      responses:
        '200':
          description: OK
          headers:
            Vary:
              schema:
                type: string
                example: Access-Control-Request-Headers
            X-Content-Type-Options:
              schema:
                type: string
                example: nosniff
            X-XSS-Protection:
              schema:
                type: integer
                example: '0'
            Cache-Control:
              schema:
                type: string
                example: no-cache, no-store, max-age=0, must-revalidate
            Pragma:
              schema:
                type: string
                example: no-cache
            Expires:
              schema:
                type: integer
                example: '0'
            X-Frame-Options:
              schema:
                type: string
                example: DENY
            Content-Type:
              schema:
                type: string
                example: application/json
            Transfer-Encoding:
              schema:
                type: string
                example: chunked
            Date:
              schema:
                type: string
                example: Fri, 06 Dec 2024 16:12:48 GMT
            Keep-Alive:
              schema:
                type: string
                example: timeout=60
            Connection:
              schema:
                type: string
                example: keep-alive
          content:
            application/json:
              schema:
                type: object
              example:
                response_schema:
                  response_code: PLUGINUSERMANAGEMENT-0000
                  response_message: Success
                response_output:
                  list:
                    pagination:
                      page: 0
                      size: 10
                      total: 1
                      total_pages: 1
                    content:
                      - id: 1
                        username: super_admin
                        name: Super Admin
                        is_active: true
                        created_at: '2024-11-25T07:28:33.959202Z'
                        created_by: null
                        last_modified_at: '2024-12-06T16:08:39.55261Z'
                        last_modified_by: null
    post:
      tags:
        - User Management > Master User
      summary: Post new User
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                username: newusername
                name: New Username
                role_ids:
                  - SUPER_ADMIN
      security:
        - bearerAuth: []
      responses:
        '200':
          description: OK
          headers:
            Vary:
              schema:
                type: string
                example: Access-Control-Request-Headers
            X-Content-Type-Options:
              schema:
                type: string
                example: nosniff
            X-XSS-Protection:
              schema:
                type: integer
                example: '0'
            Cache-Control:
              schema:
                type: string
                example: no-cache, no-store, max-age=0, must-revalidate
            Pragma:
              schema:
                type: string
                example: no-cache
            Expires:
              schema:
                type: integer
                example: '0'
            X-Frame-Options:
              schema:
                type: string
                example: DENY
            Content-Type:
              schema:
                type: string
                example: application/json
            Transfer-Encoding:
              schema:
                type: string
                example: chunked
            Date:
              schema:
                type: string
                example: Fri, 06 Dec 2024 16:17:21 GMT
            Keep-Alive:
              schema:
                type: string
                example: timeout=60
            Connection:
              schema:
                type: string
                example: keep-alive
          content:
            application/json:
              schema:
                type: object
              example:
                response_schema:
                  response_code: PLUGINUSERMANAGEMENT-0000
                  response_message: Success
                response_output:
                  detail:
                    id: 17
                    username: newusername
                    name: New Username
                    is_active: false
                    created_at: null
                    created_by: null
                    last_modified_at: null
                    last_modified_by: null
                    roles:
                      - id: SUPER_ADMIN
                        name: Super Admin
                        description: Super Admin Role
                        permissions:
                          - id: MENU_X
                            name: Menu X
                            description: Menu X description
                            permission_actions:
                              - id: MENU_X.ACTION_B
                                description: Action B on Menu X
                              - id: MENU_X.ACTION_A
                                description: Action A on Menu X
                          - id: MASTER_ROLE
                            name: Master Role
                            description: Menu Master Role
                            permission_actions:
                              - id: MASTER_ROLE.DELETE
                                description: Master Role Delete
                              - id: MASTER_ROLE.CREATE
                                description: Master Role Create
                              - id: MASTER_ROLE.UPDATE
                                description: Master Role Update
                              - id: MASTER_ROLE.READ_LIST
                                description: Master Role Read List
                              - id: MASTER_ROLE.READ_DETAIL
                                description: Master Role Read Detail
                          - id: MASTER_USER
                            name: Master User
                            description: Menu Master User
                            permission_actions:
                              - id: MASTER_USER.UPDATE
                                description: Master User Update
                              - id: MASTER_USER.CREATE
                                description: Master User Create
                              - id: MASTER_USER.READ_LIST
                                description: Master User Read List
                              - id: MASTER_USER.READ_DETAIL
                                description: Master User Read Detail
                              - id: MASTER_USER.DELETE
                                description: Master User Delete
  /api/user/{id}:
    get:
      tags:
        - User Management > Master User
      summary: Get User Detail
      security:
        - bearerAuth: []
      parameters:
        - name: id
          in: path
          schema:
            type: integer
          required: true
          example: '1'
      responses:
        '200':
          description: OK
          headers:
            Vary:
              schema:
                type: string
                example: Access-Control-Request-Headers
            X-Content-Type-Options:
              schema:
                type: string
                example: nosniff
            X-XSS-Protection:
              schema:
                type: integer
                example: '0'
            Cache-Control:
              schema:
                type: string
                example: no-cache, no-store, max-age=0, must-revalidate
            Pragma:
              schema:
                type: string
                example: no-cache
            Expires:
              schema:
                type: integer
                example: '0'
            X-Frame-Options:
              schema:
                type: string
                example: DENY
            Content-Type:
              schema:
                type: string
                example: application/json
            Transfer-Encoding:
              schema:
                type: string
                example: chunked
            Date:
              schema:
                type: string
                example: Fri, 06 Dec 2024 16:14:33 GMT
            Keep-Alive:
              schema:
                type: string
                example: timeout=60
            Connection:
              schema:
                type: string
                example: keep-alive
          content:
            application/json:
              schema:
                type: object
              example:
                response_schema:
                  response_code: PLUGINUSERMANAGEMENT-0000
                  response_message: Success
                response_output:
                  detail:
                    id: 1
                    username: super_admin
                    name: Super Admin
                    is_active: true
                    created_at: '2024-11-25T07:28:33.959202Z'
                    created_by: null
                    last_modified_at: '2024-12-06T16:08:39.55261Z'
                    last_modified_by: null
                    roles:
                      - id: SUPER_ADMIN
                        name: Super Admin
                        description: Super Admin Role
                        permissions:
                          - id: MENU_X
                            name: Menu X
                            description: Menu X description
                            permission_actions:
                              - id: MENU_X.ACTION_A
                                description: Action A on Menu X
                              - id: MENU_X.ACTION_B
                                description: Action B on Menu X
                          - id: MASTER_ROLE
                            name: Master Role
                            description: Menu Master Role
                            permission_actions:
                              - id: MASTER_ROLE.DELETE
                                description: Master Role Delete
                              - id: MASTER_ROLE.UPDATE
                                description: Master Role Update
                              - id: MASTER_ROLE.CREATE
                                description: Master Role Create
                              - id: MASTER_ROLE.READ_LIST
                                description: Master Role Read List
                              - id: MASTER_ROLE.READ_DETAIL
                                description: Master Role Read Detail
                          - id: MASTER_USER
                            name: Master User
                            description: Menu Master User
                            permission_actions:
                              - id: MASTER_USER.UPDATE
                                description: Master User Update
                              - id: MASTER_USER.CREATE
                                description: Master User Create
                              - id: MASTER_USER.READ_LIST
                                description: Master User Read List
                              - id: MASTER_USER.READ_DETAIL
                                description: Master User Read Detail
                              - id: MASTER_USER.DELETE
                                description: Master User Delete
  /api/user/17:
    put:
      tags:
        - User Management > Master User
      summary: Put Update User
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                username: newusername
                name: New 14
                role_ids:
                  - SUPER_ADMIN
      security:
        - bearerAuth: []
      responses:
        '200':
          description: OK
          headers:
            Vary:
              schema:
                type: string
                example: Access-Control-Request-Headers
            X-Content-Type-Options:
              schema:
                type: string
                example: nosniff
            X-XSS-Protection:
              schema:
                type: integer
                example: '0'
            Cache-Control:
              schema:
                type: string
                example: no-cache, no-store, max-age=0, must-revalidate
            Pragma:
              schema:
                type: string
                example: no-cache
            Expires:
              schema:
                type: integer
                example: '0'
            X-Frame-Options:
              schema:
                type: string
                example: DENY
            Content-Type:
              schema:
                type: string
                example: application/json
            Transfer-Encoding:
              schema:
                type: string
                example: chunked
            Date:
              schema:
                type: string
                example: Fri, 06 Dec 2024 16:18:38 GMT
            Keep-Alive:
              schema:
                type: string
                example: timeout=60
            Connection:
              schema:
                type: string
                example: keep-alive
          content:
            application/json:
              schema:
                type: object
              example:
                response_schema:
                  response_code: PLUGINUSERMANAGEMENT-0000
                  response_message: Success
                response_output:
                  detail:
                    id: 17
                    username: newusername
                    name: New 14
                    is_active: false
                    created_at: '2024-12-06T16:17:21.525068Z'
                    created_by: null
                    last_modified_at: '2024-12-06T16:17:21.525068Z'
                    last_modified_by: null
                    roles:
                      - id: SUPER_ADMIN
                        name: Super Admin
                        description: Super Admin Role
                        permissions:
                          - id: MENU_X
                            name: Menu X
                            description: Menu X description
                            permission_actions:
                              - id: MENU_X.ACTION_A
                                description: Action A on Menu X
                              - id: MENU_X.ACTION_B
                                description: Action B on Menu X
                          - id: MASTER_ROLE
                            name: Master Role
                            description: Menu Master Role
                            permission_actions:
                              - id: MASTER_ROLE.DELETE
                                description: Master Role Delete
                              - id: MASTER_ROLE.CREATE
                                description: Master Role Create
                              - id: MASTER_ROLE.UPDATE
                                description: Master Role Update
                              - id: MASTER_ROLE.READ_LIST
                                description: Master Role Read List
                              - id: MASTER_ROLE.READ_DETAIL
                                description: Master Role Read Detail
                          - id: MASTER_USER
                            name: Master User
                            description: Menu Master User
                            permission_actions:
                              - id: MASTER_USER.CREATE
                                description: Master User Create
                              - id: MASTER_USER.UPDATE
                                description: Master User Update
                              - id: MASTER_USER.READ_LIST
                                description: Master User Read List
                              - id: MASTER_USER.READ_DETAIL
                                description: Master User Read Detail
                              - id: MASTER_USER.DELETE
                                description: Master User Delete
    delete:
      tags:
        - User Management > Master User
      summary: Delete User
      security:
        - bearerAuth: []
      responses:
        '200':
          description: OK
          headers:
            Vary:
              schema:
                type: string
                example: Access-Control-Request-Headers
            X-Content-Type-Options:
              schema:
                type: string
                example: nosniff
            X-XSS-Protection:
              schema:
                type: integer
                example: '0'
            Cache-Control:
              schema:
                type: string
                example: no-cache, no-store, max-age=0, must-revalidate
            Pragma:
              schema:
                type: string
                example: no-cache
            Expires:
              schema:
                type: integer
                example: '0'
            X-Frame-Options:
              schema:
                type: string
                example: DENY
            Content-Type:
              schema:
                type: string
                example: application/json
            Transfer-Encoding:
              schema:
                type: string
                example: chunked
            Date:
              schema:
                type: string
                example: Fri, 06 Dec 2024 16:20:01 GMT
            Keep-Alive:
              schema:
                type: string
                example: timeout=60
            Connection:
              schema:
                type: string
                example: keep-alive
          content:
            application/json:
              schema:
                type: object
              example:
                response_schema:
                  response_code: PLUGINUSERMANAGEMENT-0000
                  response_message: Success
                response_output:
                  detail: null
  /api/permission:
    get:
      tags:
        - User Management > Master Role
      summary: Get All Permission
      security:
        - bearerAuth: []
      responses:
        '200':
          description: OK
          headers:
            Vary:
              schema:
                type: string
                example: Access-Control-Request-Headers
            X-Content-Type-Options:
              schema:
                type: string
                example: nosniff
            X-XSS-Protection:
              schema:
                type: integer
                example: '0'
            Cache-Control:
              schema:
                type: string
                example: no-cache, no-store, max-age=0, must-revalidate
            Pragma:
              schema:
                type: string
                example: no-cache
            Expires:
              schema:
                type: integer
                example: '0'
            X-Frame-Options:
              schema:
                type: string
                example: DENY
            Content-Type:
              schema:
                type: string
                example: application/json
            Transfer-Encoding:
              schema:
                type: string
                example: chunked
            Date:
              schema:
                type: string
                example: Fri, 06 Dec 2024 16:20:21 GMT
            Keep-Alive:
              schema:
                type: string
                example: timeout=60
            Connection:
              schema:
                type: string
                example: keep-alive
          content:
            application/json:
              schema:
                type: object
              example:
                response_schema:
                  response_code: PLUGINUSERMANAGEMENT-0000
                  response_message: Success
                response_output:
                  list:
                    pagination: null
                    content:
                      - id: MASTER_USER
                        name: Master User
                        description: Menu Master User
                        permission_actions:
                          - id: MASTER_USER.DELETE
                            description: Master User Delete
                          - id: MASTER_USER.UPDATE
                            description: Master User Update
                          - id: MASTER_USER.CREATE
                            description: Master User Create
                          - id: MASTER_USER.READ_DETAIL
                            description: Master User Read Detail
                          - id: MASTER_USER.READ_LIST
                            description: Master User Read List
                      - id: MASTER_ROLE
                        name: Master Role
                        description: Menu Master Role
                        permission_actions:
                          - id: MASTER_ROLE.READ_LIST
                            description: Master Role Read List
                          - id: MASTER_ROLE.CREATE
                            description: Master Role Create
                          - id: MASTER_ROLE.DELETE
                            description: Master Role Delete
                          - id: MASTER_ROLE.UPDATE
                            description: Master Role Update
                          - id: MASTER_ROLE.READ_DETAIL
                            description: Master Role Read Detail
                      - id: MENU_X
                        name: Menu X
                        description: Menu X description
                        permission_actions:
                          - id: MENU_X.ACTION_B
                            description: Action B on Menu X
                          - id: MENU_X.ACTION_A
                            description: Action A on Menu X
  /api/role/all:
    get:
      tags:
        - User Management > Master Role
      summary: Get All Role
      security:
        - bearerAuth: []
      parameters:
        - name: search
          in: query
          schema:
            type: string
      responses:
        '200':
          description: OK
          headers:
            Vary:
              schema:
                type: string
                example: Access-Control-Request-Headers
            X-Content-Type-Options:
              schema:
                type: string
                example: nosniff
            X-XSS-Protection:
              schema:
                type: integer
                example: '0'
            Cache-Control:
              schema:
                type: string
                example: no-cache, no-store, max-age=0, must-revalidate
            Pragma:
              schema:
                type: string
                example: no-cache
            Expires:
              schema:
                type: integer
                example: '0'
            X-Frame-Options:
              schema:
                type: string
                example: DENY
            Content-Type:
              schema:
                type: string
                example: application/json
            Transfer-Encoding:
              schema:
                type: string
                example: chunked
            Date:
              schema:
                type: string
                example: Fri, 06 Dec 2024 16:21:32 GMT
            Keep-Alive:
              schema:
                type: string
                example: timeout=60
            Connection:
              schema:
                type: string
                example: keep-alive
          content:
            application/json:
              schema:
                type: object
              example:
                response_schema:
                  response_code: PLUGINUSERMANAGEMENT-0000
                  response_message: Success
                response_output:
                  list:
                    pagination: null
                    content:
                      - id: SUPER_ADMIN
                        name: Super Admin
                        description: Super Admin Role
                        permissions:
                          - id: MENU_X
                            name: Menu X
                            description: Menu X description
                            permission_actions:
                              - id: MENU_X.ACTION_A
                                description: Action A on Menu X
                              - id: MENU_X.ACTION_B
                                description: Action B on Menu X
                          - id: MASTER_ROLE
                            name: Master Role
                            description: Menu Master Role
                            permission_actions:
                              - id: MASTER_ROLE.DELETE
                                description: Master Role Delete
                              - id: MASTER_ROLE.CREATE
                                description: Master Role Create
                              - id: MASTER_ROLE.UPDATE
                                description: Master Role Update
                              - id: MASTER_ROLE.READ_LIST
                                description: Master Role Read List
                              - id: MASTER_ROLE.READ_DETAIL
                                description: Master Role Read Detail
                          - id: MASTER_USER
                            name: Master User
                            description: Menu Master User
                            permission_actions:
                              - id: MASTER_USER.UPDATE
                                description: Master User Update
                              - id: MASTER_USER.CREATE
                                description: Master User Create
                              - id: MASTER_USER.READ_LIST
                                description: Master User Read List
                              - id: MASTER_USER.READ_DETAIL
                                description: Master User Read Detail
                              - id: MASTER_USER.DELETE
                                description: Master User Delete
  /api/role:
    get:
      tags:
        - User Management > Master Role
      summary: Get Role Pagination
      security:
        - bearerAuth: []
      parameters:
        - name: search
          in: query
          schema:
            type: string
        - name: page
          in: query
          schema:
            type: integer
          example: '0'
        - name: size
          in: query
          schema:
            type: integer
          example: '10'
        - name: sort
          in: query
          schema:
            type: string
          example: name,asc
      responses:
        '200':
          description: OK
          headers:
            Vary:
              schema:
                type: string
                example: Access-Control-Request-Headers
            X-Content-Type-Options:
              schema:
                type: string
                example: nosniff
            X-XSS-Protection:
              schema:
                type: integer
                example: '0'
            Cache-Control:
              schema:
                type: string
                example: no-cache, no-store, max-age=0, must-revalidate
            Pragma:
              schema:
                type: string
                example: no-cache
            Expires:
              schema:
                type: integer
                example: '0'
            X-Frame-Options:
              schema:
                type: string
                example: DENY
            Content-Type:
              schema:
                type: string
                example: application/json
            Transfer-Encoding:
              schema:
                type: string
                example: chunked
            Date:
              schema:
                type: string
                example: Fri, 06 Dec 2024 16:23:57 GMT
            Keep-Alive:
              schema:
                type: string
                example: timeout=60
            Connection:
              schema:
                type: string
                example: keep-alive
          content:
            application/json:
              schema:
                type: object
              example:
                response_schema:
                  response_code: PLUGINUSERMANAGEMENT-0000
                  response_message: Success
                response_output:
                  list:
                    pagination:
                      page: 0
                      size: 10
                      total: 1
                      total_pages: 1
                    content:
                      - id: SUPER_ADMIN
                        name: Super Admin
                        description: Super Admin Role
                        permissions:
                          - id: MENU_X
                            name: Menu X
                            description: Menu X description
                            permission_actions:
                              - id: MENU_X.ACTION_B
                                description: Action B on Menu X
                              - id: MENU_X.ACTION_A
                                description: Action A on Menu X
                          - id: MASTER_ROLE
                            name: Master Role
                            description: Menu Master Role
                            permission_actions:
                              - id: MASTER_ROLE.DELETE
                                description: Master Role Delete
                              - id: MASTER_ROLE.UPDATE
                                description: Master Role Update
                              - id: MASTER_ROLE.CREATE
                                description: Master Role Create
                              - id: MASTER_ROLE.READ_LIST
                                description: Master Role Read List
                              - id: MASTER_ROLE.READ_DETAIL
                                description: Master Role Read Detail
                          - id: MASTER_USER
                            name: Master User
                            description: Menu Master User
                            permission_actions:
                              - id: MASTER_USER.UPDATE
                                description: Master User Update
                              - id: MASTER_USER.CREATE
                                description: Master User Create
                              - id: MASTER_USER.READ_LIST
                                description: Master User Read List
                              - id: MASTER_USER.READ_DETAIL
                                description: Master User Read Detail
                              - id: MASTER_USER.DELETE
                                description: Master User Delete
    post:
      tags:
        - User Management > Master Role
      summary: Post new Role
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                id: NEW_ROLE4
                role_name: New Role4
                description: This is Demo for New Role
                permission_actions_ids:
                  - MASTER_USER.READ_LIST
                  - MASTER_USER.READ_DETAIL
      security:
        - bearerAuth: []
      responses:
        '200':
          description: OK
          headers:
            Vary:
              schema:
                type: string
                example: Access-Control-Request-Headers
            X-Content-Type-Options:
              schema:
                type: string
                example: nosniff
            X-XSS-Protection:
              schema:
                type: integer
                example: '0'
            Cache-Control:
              schema:
                type: string
                example: no-cache, no-store, max-age=0, must-revalidate
            Pragma:
              schema:
                type: string
                example: no-cache
            Expires:
              schema:
                type: integer
                example: '0'
            X-Frame-Options:
              schema:
                type: string
                example: DENY
            Content-Type:
              schema:
                type: string
                example: application/json
            Transfer-Encoding:
              schema:
                type: string
                example: chunked
            Date:
              schema:
                type: string
                example: Fri, 06 Dec 2024 16:27:11 GMT
            Keep-Alive:
              schema:
                type: string
                example: timeout=60
            Connection:
              schema:
                type: string
                example: keep-alive
          content:
            application/json:
              schema:
                type: object
              example:
                response_schema:
                  response_code: PLUGINUSERMANAGEMENT-0000
                  response_message: Success
                response_output:
                  detail:
                    id: NEW_ROLE4
                    name: New Role4
                    description: This is Demo for New Role
                    permissions:
                      - id: MASTER_USER
                        name: Master User
                        description: Menu Master User
                        permission_actions:
                          - id: MASTER_USER.READ_LIST
                            description: Master User Read List
                          - id: MASTER_USER.READ_DETAIL
                            description: Master User Read Detail
  /api/role/{id}:
    get:
      tags:
        - User Management > Master Role
      summary: Get Role Detail
      security:
        - bearerAuth: []
      parameters:
        - name: id
          in: path
          schema:
            type: string
          required: true
          example: SUPER_ADMIN
      responses:
        '200':
          description: OK
          headers:
            Vary:
              schema:
                type: string
                example: Access-Control-Request-Headers
            X-Content-Type-Options:
              schema:
                type: string
                example: nosniff
            X-XSS-Protection:
              schema:
                type: integer
                example: '0'
            Cache-Control:
              schema:
                type: string
                example: no-cache, no-store, max-age=0, must-revalidate
            Pragma:
              schema:
                type: string
                example: no-cache
            Expires:
              schema:
                type: integer
                example: '0'
            X-Frame-Options:
              schema:
                type: string
                example: DENY
            Content-Type:
              schema:
                type: string
                example: application/json
            Transfer-Encoding:
              schema:
                type: string
                example: chunked
            Date:
              schema:
                type: string
                example: Fri, 06 Dec 2024 16:25:28 GMT
            Keep-Alive:
              schema:
                type: string
                example: timeout=60
            Connection:
              schema:
                type: string
                example: keep-alive
          content:
            application/json:
              schema:
                type: object
              example:
                response_schema:
                  response_code: PLUGINUSERMANAGEMENT-0000
                  response_message: Success
                response_output:
                  detail:
                    id: SUPER_ADMIN
                    name: Super Admin
                    description: Super Admin Role
                    permissions:
                      - id: MENU_X
                        name: Menu X
                        description: Menu X description
                        permission_actions:
                          - id: MENU_X.ACTION_B
                            description: Action B on Menu X
                          - id: MENU_X.ACTION_A
                            description: Action A on Menu X
                      - id: MASTER_ROLE
                        name: Master Role
                        description: Menu Master Role
                        permission_actions:
                          - id: MASTER_ROLE.DELETE
                            description: Master Role Delete
                          - id: MASTER_ROLE.UPDATE
                            description: Master Role Update
                          - id: MASTER_ROLE.CREATE
                            description: Master Role Create
                          - id: MASTER_ROLE.READ_LIST
                            description: Master Role Read List
                          - id: MASTER_ROLE.READ_DETAIL
                            description: Master Role Read Detail
                      - id: MASTER_USER
                        name: Master User
                        description: Menu Master User
                        permission_actions:
                          - id: MASTER_USER.UPDATE
                            description: Master User Update
                          - id: MASTER_USER.CREATE
                            description: Master User Create
                          - id: MASTER_USER.READ_LIST
                            description: Master User Read List
                          - id: MASTER_USER.READ_DETAIL
                            description: Master User Read Detail
                          - id: MASTER_USER.DELETE
                            description: Master User Delete
  /api/role/NEW_ROLE4:
    put:
      tags:
        - User Management > Master Role
      summary: Put Update Role
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                role_name: Test Update
                description: This is Demo for New Role
                permission_actions_ids:
                  - MASTER_USER.READ_LIST
      security:
        - bearerAuth: []
      responses:
        '200':
          description: OK
          headers:
            Vary:
              schema:
                type: string
                example: Access-Control-Request-Headers
            X-Content-Type-Options:
              schema:
                type: string
                example: nosniff
            X-XSS-Protection:
              schema:
                type: integer
                example: '0'
            Cache-Control:
              schema:
                type: string
                example: no-cache, no-store, max-age=0, must-revalidate
            Pragma:
              schema:
                type: string
                example: no-cache
            Expires:
              schema:
                type: integer
                example: '0'
            X-Frame-Options:
              schema:
                type: string
                example: DENY
            Content-Type:
              schema:
                type: string
                example: application/json
            Transfer-Encoding:
              schema:
                type: string
                example: chunked
            Date:
              schema:
                type: string
                example: Fri, 06 Dec 2024 16:29:16 GMT
            Keep-Alive:
              schema:
                type: string
                example: timeout=60
            Connection:
              schema:
                type: string
                example: keep-alive
          content:
            application/json:
              schema:
                type: object
              example:
                response_schema:
                  response_code: PLUGINUSERMANAGEMENT-0000
                  response_message: Success
                response_output:
                  detail:
                    id: NEW_ROLE4
                    name: Test Update
                    description: This is Demo for New Role
                    permissions:
                      - id: MASTER_USER
                        name: Master User
                        description: Menu Master User
                        permission_actions:
                          - id: MASTER_USER.READ_LIST
                            description: Master User Read List
    delete:
      tags:
        - User Management > Master Role
      summary: Delete Role
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
